### ISSUE TITLE
Question: Roadmap for development

### ISSUE THREAD

**Issue by seandavi** [singularityhub/singularity-python#30] opened 2016-12-23 16:41 UTC
I think we have some use cases for this software to integrate singularity containers into our python-based scientific workflows. I am just curious about current development activity and plans for a "first release" type of thing. I am not trying to hand out work, but just curious what your thoughts are.

Thanks.

**Comment by vsoch** [comment] 2016-12-23 17:20
Hey @seandavi! A lot of the functionality has moved into singularity hub (Django) and the docker functions that singularity-Python used to provide have moved into the core singularity software. I have it on my todo to update this software, and my plan was to remove a lot of the redundancy. Could you tell me about your use case so I can best advise about integrating singularity?

**Comment by seandavi** [comment] 2016-12-23 17:30
Thanks, @vsoch, for the quick reply. The main use case that I had in mind is simply replacing directly-installed command-line software with singularity containers with the same software.  This would make it very easy to write reproducible tasks without a need to install software, set paths, etc., on the host system.  

For example, the `shell` part of this script:

https://bitbucket.org/snakemake/snakemake-wrappers/src/62b507647dde443371c4bd75bead4f00e7ff7d80/bio/delly/wrapper.py?at=master&fileviewer=file-view-default

would be replaced either with a call to singularity directly, or to a python utility (supplied by this package?).

**Comment by vsoch** [comment] 2016-12-23 17:51
ah, fantastic! My recommendation would be to have a script like that as the container's `runscript`, which you can do with a build specification like the following:

Here this is in the build specification file, a file called Singularity that you can use the build the image (or soon serve on singularity hub and it will build for you). The Bootstrap From is just a standard OS that I picked - you don't have to use a Docker image, but I find this easy to do:

      BootStrap: docker
      From: ubuntu:latest

      %runscript

       exec /usr/bin/python /path/to/wrapper.py "$@"

      %post
       apt-get update
       apt-get install -y git
       git clone ..... 
       (insert more installation / etc stuffs here for your software)
       echo "Here the container is done bootstrapping!"

You would do the above as follows, on a local machine where you have sudo:

      sudo singularity create biodelly.img
      sudo singularity bootstrap biodelly.img Singularity

then you would transfer your image to the cluster/place it will be run (without sudo) and run in any of the following ways:

      singularity run biodelly.img input 1 arg1....
      singularity shell biodelly.img
      singularity exec biodelly.img echo "Hello World!"

The above is working, now. Then (soon/in the future) if your repo is build directly on Singularity hub, you would push that file `Singularity` to the repo, and the image would be built automatically, and you would use on command line with  a  different endpoint:

      singularity run shub://username:biodelly input 1 arg1....

The build would happen in the cloud, and it uses the build.py file I pointed out! Does the above meet your needs, or is there additional functionality we could chat about that might be integrated into singularity-python?

**Comment by seandavi** [comment] 2016-12-23 18:25
Nice!  I think this is pretty close, but the python work will need to be done outside the singularity container, as the python formatting is done in the context of the host OS, not inside the container.  In other words, I think I would probably do something more like this for the runscript:

```
exec /bin/bash "$@"
```

And the `shell()` call in the python wrapper.py script would then become:

```
shell(
    "singularity run shub://username:biodelly "
    "OMP_NUM_THREADS={snakemake.threads} delly {snakemake.params} "
    "{exclude} -t {snakemake.wildcards.type} -g {snakemake.input.ref} "
    "-o {snakemake.output[0]} {snakemake.input.samples} &> {snakemake.log}")
```

Does that seem to make sense to you?

As an aside, how far off is singularity hub? That is really key for allowing reproducibility without having to create a full environment. Again, just curious.

**Comment by vsoch** [comment] 2016-12-23 19:47
Could you give more detail about the "python formatting done in context of the host OS?" Singularity is pretty seamless between host and container, so there might be a solution that would work inside the container.

If you don't have a runscript at all, it defaults to shell, and if you want to send a command directly to something inside the container you could use `exec`.

Ahh `OMP_NUM_THREADS` ... is this something with Open MPI? Have you seen [this post](http://singularity.lbl.gov/docs-hpc#integration-with-mpi)? I'm not a huge user, but we have a lot of users on our slack using MPI, and I know the way it's done is counter intuitive / different than the norm. I think it might make sense for you to touch bases with either other users on slack, or chat with Greg - let me know your thoughts on the above and we will figure out the right direction to go in! 

And to answer your question, we just submit a first paper for Singularity, and Singularity Hub should follow in the next few months. The core infrastructure is up and working, but it's not technically publicly announced, because I am still going to add some additional features and likely move to a database with encryption and more redundancy for the final version (right now it's postgres docker image for easy workings)!

**Comment by seandavi** [comment] 2016-12-23 20:00
OMP refers to OpenMP, not MPI, so I think this is likely a software-installation-in-the-container and not more complicated.  There is no interprocess communication here that extends beyond the container.  

As for the python piece, the `wrapper.py` is run in the context of a parent python process that has access to the variables inside the `{}`.  Running that parent python process is kicked off as a slurm job directly, so I cannot see an easy way (or a reason) to try to run the wrapper code inside the container.  

As for Singularity Hub, I suspect that you meant that you are using "postgres singularity image", right?  ; )

**Comment by vsoch** [comment] 2016-12-23 20:07
Ok, that definitely makes sense. In case it's useful, we do have [integration with slurm](https://github.com/singularityware/singularity/tree/master/src/slurm), although I haven't tested this myself. Another interesting avenue for running workflows that I just stumbled on this morning is also [nextflow](https://www.nextflow.io/blog/2016/more-fun-containers-hpc.html). Maybe @pditommaso could comment on your use case?

haha, no, it's postgres Docker! I have love for many (not all) containers... Docker is one of them. I Dockerize everything that doesn't need to be run on a cluster, or in many cases, [just do both](https://researchapps.github.io/clinical/reproducibility/2016/12/01/singularity-pefinder/). It's like selecting between two of my favorite foods... there is plenty of room for both! *burp*

**Comment by seandavi** [comment] 2016-12-23 20:16
If you like thinking about pipelines, see here:

https://github.com/pditommaso/awesome-pipeline

Yes, I have used nextflow, also.  At the end-of-the-day, replacing a system-specific command (need to have PATH set correctly or use absolute paths) with a call to run a containerized version is a very powerful paradigm that is really orthogonal to the actual workflow framework.

**Comment by vsoch** [comment] 2016-12-23 20:45
oh my lord. That is a heck of a lot of ways to do it. Yes, I definitely need to think about this, for Singularity Hub... which I'd like to be mostly agnostic to which of the things from that list is used. Thanks!

**Comment by pditommaso** [comment] 2016-12-23 21:12
@seandavi Yes, you should use `singularity exec <command>` instead of `singularity run`, that would allow you to invoke it from the snakemake shell.

**Comment by vsoch** [comment] 2016-12-28 23:07
hey @seandavi ! I've done a bunch of changes that well define the scope of singularity-python - right now it's optimized for on demand visualizations, comparisons of containers, and building of images (mostly for the google cloud right now). Singularity Hub is likely going to be the tool that you will be interested in, and I've done substantial work on it over break, and expect to be putting up a beta version in early January. Is there anything I didn't address in this issue, or is it ok to close?

**Closed as completed** 2017-01-12 01:22 UTC
